/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CtrlResponsable;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modelo.ClsConexion;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.MtoResponsable;
import modelo.ClsValidaciones;
import modelo.MtoBitacoras;
import controlador.CtrlLoginUsuario;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author katy0
 */
public class FrmAdministrarResponsable extends javax.swing.JInternalFrame {

    CtrlLoginUsuario mod;
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
    CtrlResponsable ctrl = new CtrlResponsable();
    ClsValidaciones val = new ClsValidaciones();

    /**
     * Creates new form GestionarResponsableForm
     */
    public FrmAdministrarResponsable() {
        initComponents();

    }

    public FrmAdministrarResponsable(CtrlLoginUsuario mod) {
        initComponents();
        this.mod = mod;
        System.out.println(mod.getId_usuario());
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        tResponsables.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 18));
        tResponsables.getTableHeader().setOpaque(false);
        tResponsables.getTableHeader().setBackground(new Color(33, 37, 41));
        tResponsables.getTableHeader().setForeground(new Color(254, 254, 254));

        //Llenando jTable
        modelo.addColumn("identifi");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DUI");
        modelo.addColumn("Teléfono");
        modelo.addColumn("E-mail");
        modelo.addColumn("Parentesco");
        modelo.addColumn("Estado");
        tResponsables.setModel(modelo);
        tResponsables.getColumnModel().getColumn(0).setMinWidth(0);
        tResponsables.getColumnModel().getColumn(0).setMaxWidth(0);
        tResponsables.getColumnModel().getColumn(5).setMinWidth(0);
        tResponsables.getColumnModel().getColumn(5).setMaxWidth(0);
        tResponsables.getColumnModel().getColumn(6).setMinWidth(0);
        tResponsables.getColumnModel().getColumn(6).setMaxWidth(0);
        tResponsables.getColumnModel().getColumn(7).setMinWidth(0);
        tResponsables.getColumnModel().getColumn(7).setMaxWidth(0);
        this.vaciarTabla();
        this.mostrarResponsables();

        this.llenarParentesco();
        this.centrarColumnas();
        
        btnActualizar.setEnabled(false);
        btnSuspender.setEnabled(false);
        btnActivar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "deprecated"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnActivar = new javax.swing.JButton();
        btnCorreo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tResponsables = new javax.swing.JTable();
        btnSuspender = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JTextField();
        jLayer1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDUI = new javax.swing.JFormattedTextField();
        jLayer2 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbParentesco = new javax.swing.JComboBox<>();
        jTelefono = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(33, 37, 41));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Gestionar Responsables ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        btnActivar.setBackground(new java.awt.Color(33, 37, 41));
        btnActivar.setForeground(new java.awt.Color(254, 254, 254));
        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActivarDefault.png"))); // NOI18N
        btnActivar.setBorder(null);
        btnActivar.setContentAreaFilled(false);
        btnActivar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActivar.setFocusPainted(false);
        btnActivar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActivarRollover.png"))); // NOI18N
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 140, 70));

        btnCorreo.setBackground(new java.awt.Color(33, 37, 41));
        btnCorreo.setForeground(new java.awt.Color(254, 254, 254));
        btnCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEnviarCorreo_default.png"))); // NOI18N
        btnCorreo.setBorder(null);
        btnCorreo.setContentAreaFilled(false);
        btnCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCorreo.setFocusPainted(false);
        btnCorreo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEnviarCorreo_rollover.png"))); // NOI18N
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 140, 70));

        btnActualizar.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_default.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_rollover.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 140, 70));

        tResponsables = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tResponsables.setBackground(new java.awt.Color(33, 37, 41));
        tResponsables.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tResponsables.setForeground(new java.awt.Color(255, 255, 255));
        tResponsables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tResponsables.setFocusable(false);
        tResponsables.setGridColor(new java.awt.Color(64, 65, 65));
        tResponsables.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tResponsables.setRowHeight(30);
        tResponsables.setSelectionBackground(new java.awt.Color(45, 252, 119));
        tResponsables.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tResponsables.setShowVerticalLines(false);
        tResponsables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tResponsablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tResponsables);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 960, 320));

        btnSuspender.setBackground(new java.awt.Color(33, 37, 41));
        btnSuspender.setForeground(new java.awt.Color(254, 254, 254));
        btnSuspender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSuspender_default.png"))); // NOI18N
        btnSuspender.setBorder(null);
        btnSuspender.setContentAreaFilled(false);
        btnSuspender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSuspender.setFocusPainted(false);
        btnSuspender.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSuspender_rollover.png"))); // NOI18N
        btnSuspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuspender, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 140, 70));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Digite lo que desea buscar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jBuscar.setBackground(new java.awt.Color(33, 37, 41));
        jBuscar.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jBuscar.setForeground(new java.awt.Color(254, 254, 254));
        jBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 620, 30));

        jLayer1.setNextFocusableComponent(jLayer2);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Nombre:");
        jLayer1.add(jLabel5);
        jLabel5.setBounds(20, 0, 60, 30);

        jNombre.setBackground(new java.awt.Color(33, 37, 41));
        jNombre.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jNombre.setForeground(new java.awt.Color(254, 254, 254));
        jNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNombreKeyTyped(evt);
            }
        });
        jLayer1.add(jNombre);
        jNombre.setBounds(20, 30, 250, 30);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Apellido:");
        jLayer1.add(jLabel6);
        jLabel6.setBounds(20, 70, 61, 30);

        jApellido.setBackground(new java.awt.Color(33, 37, 41));
        jApellido.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jApellido.setForeground(new java.awt.Color(254, 254, 254));
        jApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jApellidoKeyTyped(evt);
            }
        });
        jLayer1.add(jApellido);
        jApellido.setBounds(20, 100, 250, 30);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("DUI:");
        jLayer1.add(jLabel7);
        jLabel7.setBounds(20, 140, 30, 30);

        jDUI.setBackground(new java.awt.Color(33, 37, 41));
        jDUI.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jDUI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDUI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDUI.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jDUI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDUIKeyPressed(evt);
            }
        });
        jLayer1.add(jDUI);
        jDUI.setBounds(20, 170, 250, 30);

        jPanel1.add(jLayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 280, 220));

        jLayer2.setNextFocusableComponent(jLayer1);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Email:");
        jLayer2.add(jLabel11);
        jLabel11.setBounds(10, 80, 44, 30);

        jEmail.setBackground(new java.awt.Color(33, 37, 41));
        jEmail.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jEmail.setForeground(new java.awt.Color(254, 254, 254));
        jEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jEmailKeyTyped(evt);
            }
        });
        jLayer2.add(jEmail);
        jEmail.setBounds(10, 110, 300, 30);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Teléfono:");
        jLayer2.add(jLabel9);
        jLabel9.setBounds(10, 10, 64, 30);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Parentesco:");
        jLayer2.add(jLabel8);
        jLabel8.setBounds(10, 150, 84, 30);

        cbParentesco.setBackground(new java.awt.Color(33, 37, 41));
        cbParentesco.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbParentesco.setForeground(new java.awt.Color(255, 255, 255));
        cbParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbParentesco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbParentescoKeyPressed(evt);
            }
        });
        jLayer2.add(cbParentesco);
        cbParentesco.setBounds(10, 180, 290, 30);

        jTelefono.setBackground(new java.awt.Color(33, 37, 41));
        jTelefono.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTelefono.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTelefonoKeyPressed(evt);
            }
        });
        jLayer2.add(jTelefono);
        jTelefono.setBounds(10, 40, 270, 30);

        jPanel1.add(jLayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 320, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    public void llenarParentesco() {
        MtoResponsable a = new MtoResponsable();
        cbParentesco.setModel(a.llenarParentesco());
    }

    public void vaciarTabla() {
        int filas = tResponsables.getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
    }

    public void vaciarCampos() {
        btnActualizar.setEnabled(false);
        btnSuspender.setEnabled(false);
        btnCorreo.setEnabled(false);
        btnActivar.setEnabled(false);
        jNombre.setText("");
        jDUI.setText("");
        jNombre.setText("");
        jEmail.setText("");
        jTelefono.setText("");
        jApellido.setText("");
        btnActualizar.setEnabled(false);
        btnSuspender.setEnabled(false);
        btnActivar.setEnabled(false);
    }
    
    public void centrarColumnas(){
        centrado.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < 8; i++) {
            tResponsables.getColumnModel().getColumn(i).setCellRenderer(centrado);
        }
    }

    public void mostrarResponsables() {

        ClsConexion con = new ClsConexion();
        Connection datos;
        try {
            datos = con.conectar();
            String sql = "SELECT r.id_responsable, r.nombre, r.apellido, r.dui, r.telefono, r.email, p.parentesco, e.estado_responsable FROM responsable r, parentesco p, estado_responsable e "
                    + "WHERE r.id_parentesco = p.id_parentesco AND r.id_estado_responsable = e.id_estado_responsable";
            PreparedStatement dato = datos.prepareStatement(sql);
            ResultSet rs = dato.executeQuery();
            while (rs.next()) {
                Object fila[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)};
                modelo.addRow(fila);
            }
            tResponsables.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorreoActionPerformed
        FrmEnviarCorreo formulario = new FrmEnviarCorreo();
        formulario.setVisible(true);
    }//GEN-LAST:event_btnCorreoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (jNombre.getText().trim().equals("") || jApellido.getText().trim().equals("") || jDUI.getText().trim().equals("") || jTelefono.getText().trim().equals("") || jEmail.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campos vacios.", "Rellene los campos faltantes.", JOptionPane.WARNING_MESSAGE);
        } 
        else if(val.email(jEmail.getText()))
        {
            MtoResponsable mto = new MtoResponsable();
            ctrl.setNombre(jNombre.getText());
            ctrl.setApellido(jApellido.getText());
            ctrl.setDui(jDUI.getText());
            ctrl.setEmail(jEmail.getText());
            ctrl.setTelefono(jTelefono.getText());
            if (!mto.verificarDuiExistente()) {
                JOptionPane.showMessageDialog(null, "El número de DUI que intenta ingresar ya está en uso", "DUI ya existente", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                if (mto.actualizarResponsable(String.valueOf(cbParentesco.getSelectedItem()))) {
                    JOptionPane.showMessageDialog(null, "Se han actualizado los datos correctamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
                    MtoBitacoras add = new MtoBitacoras();
                    int id = add.capturarIdBitacora() + 1;
                    mod.setId_usuario(mod.getId_usuario());
                    mod.setId_bitacora(id);
                    add.agregarBitacoraActualizarResponsable(mod);
                    jBuscar.setText("");
                    String busqueda = jBuscar.getText();
                    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
                    tResponsables.setRowSorter(tr);
                    tr.setRowFilter(RowFilter.regexFilter(busqueda));
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
            
            vaciarCampos();
            vaciarTabla();
            mostrarResponsables();
            //System.out.println(txtNombre.getText() + " " + txtApellido.getText() + " " + txtDui.getText() + " " + txtTelefono.getText() + " " + txtEmail.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Correo invalido.","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSuspenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspenderActionPerformed
        MtoResponsable mto = new MtoResponsable();
        if (mto.suspenderResponsable()) {
            JOptionPane.showMessageDialog(null, "El usuario ha sido suspendido de forma exitosa.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            jBuscar.setText("");
            MtoBitacoras add = new MtoBitacoras();
            int id = add.capturarIdBitacora() + 1;
            mod.setId_usuario(mod.getId_usuario());
            mod.setId_bitacora(id);
            add.agregarBitacoraSuspenderResponsable(mod);
            String busqueda = jBuscar.getText();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
            tResponsables.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(busqueda));
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
        vaciarCampos();
        vaciarTabla();
        mostrarResponsables();
    }//GEN-LAST:event_btnSuspenderActionPerformed

    private void tResponsablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tResponsablesMouseClicked
        //Obtener fila seleccionada
        int fila = tResponsables.getSelectedRow();

        //Creando objeto de controlador
        CtrlResponsable ctr = new CtrlResponsable();
        MtoResponsable mto = new MtoResponsable();
        ctr.setIdResponsable(Integer.parseInt((String) tResponsables.getValueAt(fila, 0)));

        mto.obtenerIdEstado();
        if (ctr.getIdEstado() == 3) {
            btnActualizar.setEnabled(false);
            btnSuspender.setEnabled(false);
            btnCorreo.setEnabled(false);
            btnActivar.setEnabled(true);
        } else {
            btnActualizar.setEnabled(true);
            btnSuspender.setEnabled(true);
            btnCorreo.setEnabled(true);
            btnActivar.setEnabled(false);
        }

        //Obteniendo valores de la tabla
        jNombre.setText(String.valueOf(tResponsables.getValueAt(fila, 1)));
        jApellido.setText(String.valueOf(tResponsables.getValueAt(fila, 2)));
        jDUI.setText(String.valueOf(tResponsables.getValueAt(fila, 3)));
        jTelefono.setText(String.valueOf(tResponsables.getValueAt(fila, 4)));
        jEmail.setText(String.valueOf(tResponsables.getValueAt(fila, 5)));
        cbParentesco.setSelectedItem(String.valueOf(tResponsables.getValueAt(fila, 6)));
        System.out.println(ctr.getIdResponsable());
    }//GEN-LAST:event_tResponsablesMouseClicked

    private void jBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyReleased
        String busqueda = jBuscar.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
        tResponsables.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(busqueda));
    }//GEN-LAST:event_jBuscarKeyReleased

    private void jBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isWhitespace(c) && c != '@' && c != '.' && c != '_') {
            val.verificarAlfanumerico(evt);
        }
    }//GEN-LAST:event_jBuscarKeyTyped

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        MtoResponsable mto = new MtoResponsable();
        if (mto.activarResponsable()) {
            JOptionPane.showMessageDialog(null, "El responsable ha sido activado de forma exitosa.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            MtoBitacoras add = new MtoBitacoras();
            int id = add.capturarIdBitacora() + 1;
            mod.setId_usuario(mod.getId_usuario());
            mod.setId_bitacora(id);
            add.agregarBitacoraActivarResponsable(mod);
            jBuscar.setText("");
            String busqueda = jBuscar.getText();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
            tResponsables.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(busqueda));
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
        vaciarCampos();
        vaciarTabla();
        mostrarResponsables();

    }//GEN-LAST:event_btnActivarActionPerformed

    private void jNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNombreKeyTyped
        val.verificarLetras(evt);
    }//GEN-LAST:event_jNombreKeyTyped

    private void jApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jApellidoKeyTyped
        val.verificarLetras(evt);
    }//GEN-LAST:event_jApellidoKeyTyped

    private void jEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailKeyTyped

    private void jNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNombreKeyPressed
        val.verificarPegar(evt);
        
        String Caracteres = jNombre.getText();
        if(Caracteres.length()>=30){
            jNombre.setText("");
            JOptionPane.showMessageDialog(null, "Limite de carácteres alcanzado.","Aviso",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jNombreKeyPressed

    private void jApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jApellidoKeyPressed
        val.verificarPegar(evt);
        
        String Caracteres = jApellido.getText();
        if(Caracteres.length()>=30){
            jApellido.setText("");
            JOptionPane.showMessageDialog(null, "Limite de carácteres alcanzado.","Aviso",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jApellidoKeyPressed

    private void jEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailKeyPressed
        val.verificarPegar(evt);
        
        String Caracteres = jEmail.getText();
        if(Caracteres.length()>=50){
            jEmail.setText("");
            JOptionPane.showMessageDialog(null, "Limite de carácteres alcanzado.","Aviso",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jEmailKeyPressed

    private void jDUIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDUIKeyPressed
        // TODO add your handling code here:
        val.verificarPegar(evt);
    }//GEN-LAST:event_jDUIKeyPressed

    private void jTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTelefonoKeyPressed
        // TODO add your handling code here:
        val.verificarPegar(evt);
    }//GEN-LAST:event_jTelefonoKeyPressed

    private void cbParentescoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbParentescoKeyPressed
        // TODO add your handling code here:
        val.verificarPegar(evt);
    }//GEN-LAST:event_cbParentescoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnSuspender;
    private javax.swing.JComboBox<String> cbParentesco;
    private javax.swing.JTextField jApellido;
    private javax.swing.JTextField jBuscar;
    private javax.swing.JFormattedTextField jDUI;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayer1;
    private javax.swing.JLayeredPane jLayer2;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTelefono;
    private javax.swing.JTable tResponsables;
    // End of variables declaration//GEN-END:variables
}
