/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CtrlResponsable;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modelo.Conexion;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.MtoResponsable;
import modelo.Validaciones;

/**
 *
 * @author katy0
 */
public class frmGestionarResponsable extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    CtrlResponsable ctrl = new CtrlResponsable();
    Validaciones val = new Validaciones();
    /**
     * Creates new form GestionarResponsableForm
     */
    public frmGestionarResponsable() {
        initComponents();
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
         tResponsables.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 18));
        tResponsables.getTableHeader().setOpaque(false);
        tResponsables.getTableHeader().setBackground(new Color(33, 37, 41));
        tResponsables.getTableHeader().setForeground(new Color(254,254,254));
        
        //Llenando jTable
        modelo.addColumn("identifi");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DUI");
        modelo.addColumn("Teléfono");
        modelo.addColumn("E-mail");
        modelo.addColumn("Parentesco");
        modelo.addColumn("Estado");
        tResponsables.setModel(modelo);
        tResponsables.getColumnModel().getColumn(0).setMinWidth(0);
        tResponsables.getColumnModel().getColumn(0).setMaxWidth(0);
        this.vaciarTabla();
        this.mostrarResponsables();
        
        this.llenarParentesco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "deprecated"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnActivar = new javax.swing.JButton();
        btnCorreo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tResponsables = new javax.swing.JTable();
        btnSuspender = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLayer1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDui = new javax.swing.JFormattedTextField();
        jLayer2 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbParentesco = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(33, 37, 41));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Gestionar Responsables ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        btnActivar.setBackground(new java.awt.Color(33, 37, 41));
        btnActivar.setForeground(new java.awt.Color(254, 254, 254));
        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActivarDefault.png"))); // NOI18N
        btnActivar.setBorder(null);
        btnActivar.setContentAreaFilled(false);
        btnActivar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActivar.setFocusPainted(false);
        btnActivar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActivarRollover.png"))); // NOI18N
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 140, 70));

        btnCorreo.setBackground(new java.awt.Color(33, 37, 41));
        btnCorreo.setForeground(new java.awt.Color(254, 254, 254));
        btnCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEnviarCorreo_default.png"))); // NOI18N
        btnCorreo.setBorder(null);
        btnCorreo.setContentAreaFilled(false);
        btnCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCorreo.setFocusPainted(false);
        btnCorreo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEnviarCorreo_rollover.png"))); // NOI18N
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 140, 70));

        btnActualizar.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_default.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_rollover.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 140, 70));

        tResponsables.setBackground(new java.awt.Color(33, 37, 41));
        tResponsables.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tResponsables.setForeground(new java.awt.Color(255, 255, 255));
        tResponsables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tResponsables.setFocusable(false);
        tResponsables.setGridColor(new java.awt.Color(64, 65, 65));
        tResponsables.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tResponsables.setRowHeight(30);
        tResponsables.setSelectionBackground(new java.awt.Color(45, 252, 119));
        tResponsables.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tResponsables.setShowVerticalLines(false);
        tResponsables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tResponsablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tResponsables);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 960, 320));

        btnSuspender.setBackground(new java.awt.Color(33, 37, 41));
        btnSuspender.setForeground(new java.awt.Color(254, 254, 254));
        btnSuspender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSuspender_default.png"))); // NOI18N
        btnSuspender.setBorder(null);
        btnSuspender.setContentAreaFilled(false);
        btnSuspender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSuspender.setFocusPainted(false);
        btnSuspender.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSuspender_rollover.png"))); // NOI18N
        btnSuspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuspender, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 140, 70));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Digite lo que desea buscar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(33, 37, 41));
        txtBuscar.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(254, 254, 254));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 620, 30));

        jLayer1.setNextFocusableComponent(jLayer2);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Nombre:");
        jLayer1.add(jLabel5);
        jLabel5.setBounds(20, 0, 60, 30);

        txtNombre.setBackground(new java.awt.Color(33, 37, 41));
        txtNombre.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(254, 254, 254));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jLayer1.add(txtNombre);
        txtNombre.setBounds(20, 30, 250, 30);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Apellido:");
        jLayer1.add(jLabel6);
        jLabel6.setBounds(20, 70, 61, 30);

        txtApellido.setBackground(new java.awt.Color(33, 37, 41));
        txtApellido.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(254, 254, 254));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jLayer1.add(txtApellido);
        txtApellido.setBounds(20, 100, 250, 30);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("DUI:");
        jLayer1.add(jLabel7);
        jLabel7.setBounds(20, 140, 30, 30);

        txtDui.setBackground(new java.awt.Color(33, 37, 41));
        txtDui.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDui.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDui.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLayer1.add(txtDui);
        txtDui.setBounds(20, 170, 250, 30);

        jPanel1.add(jLayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 280, 220));

        jLayer2.setNextFocusableComponent(jLayer1);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Email:");
        jLayer2.add(jLabel11);
        jLabel11.setBounds(10, 80, 44, 30);

        txtEmail.setBackground(new java.awt.Color(33, 37, 41));
        txtEmail.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(254, 254, 254));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jLayer2.add(txtEmail);
        txtEmail.setBounds(10, 110, 300, 30);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Teléfono:");
        jLayer2.add(jLabel9);
        jLabel9.setBounds(10, 10, 64, 30);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Parentesco:");
        jLayer2.add(jLabel8);
        jLabel8.setBounds(10, 150, 84, 30);

        cbParentesco.setBackground(new java.awt.Color(33, 37, 41));
        cbParentesco.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbParentesco.setForeground(new java.awt.Color(255, 255, 255));
        cbParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbParentesco.setBorder(null);
        jLayer2.add(cbParentesco);
        cbParentesco.setBounds(10, 180, 290, 30);

        txtTelefono.setBackground(new java.awt.Color(33, 37, 41));
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLayer2.add(txtTelefono);
        txtTelefono.setBounds(10, 40, 270, 30);

        jPanel1.add(jLayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 320, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    public void llenarParentesco(){
        MtoResponsable a = new MtoResponsable();
        cbParentesco.setModel(a.llenarParentesco());
    }
    
    public void vaciarTabla(){
       int filas = tResponsables.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        } 
    }
    
    public void vaciarCampos(){
        btnActualizar.setEnabled(false);
        btnSuspender.setEnabled(false);
        btnCorreo.setEnabled(false);
        btnActivar.setEnabled(false);
        txtNombre.setText("");
        txtDui.setText("");
        txtNombre.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtApellido.setText("");
    }
    
    public void mostrarResponsables(){
        
        Conexion con = new Conexion();
        Connection datos;
        try
        {
            datos = con.conectar();
            String sql = "SELECT r.id_responsable, r.nombre, r.apellido, r.dui, r.telefono, r.email, p.parentesco, e.estado_responsable FROM responsable r, parentesco p, estado_responsable e "
                    + "WHERE r.id_parentesco = p.id_parentesco AND r.id_estado_responsable = e.id_estado_responsable";
            PreparedStatement dato = datos.prepareStatement(sql);
            ResultSet rs = dato.executeQuery();
            while(rs.next()){
                Object fila[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)};
                modelo.addRow(fila);
            }
            tResponsables.setModel(modelo);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorreoActionPerformed
        frmCorreo formulario = new frmCorreo();
        formulario.setVisible(true);
    }//GEN-LAST:event_btnCorreoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(txtNombre.getText().trim().equals("") || txtApellido.getText().trim().equals("") || txtDui.getText().trim().equals("") || txtTelefono.getText().trim().equals("") || txtEmail.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campos vacios.","Rellene los campos faltantes.",JOptionPane.WARNING_MESSAGE);
        }else{
            MtoResponsable mto = new MtoResponsable();
            ctrl.setNombre(txtNombre.getText());
            ctrl.setApellido(txtApellido.getText());
            ctrl.setDui(txtDui.getText());
            ctrl.setEmail(txtEmail.getText());
            ctrl.setTelefono(txtTelefono.getText());
            if (mto.actualizarResponsable(String.valueOf(cbParentesco.getSelectedItem()))) {
                JOptionPane.showMessageDialog(null, "Se han actualizado los datos correctamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
                txtBuscar.setText("");
                String busqueda = txtBuscar.getText();
                TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
                tResponsables.setRowSorter(tr);
                tr.setRowFilter(RowFilter.regexFilter(busqueda));
            }else{
                JOptionPane.showMessageDialog(null, "Error");
            }
            vaciarCampos();
            vaciarTabla();
            mostrarResponsables();
            //System.out.println(txtNombre.getText() + " " + txtApellido.getText() + " " + txtDui.getText() + " " + txtTelefono.getText() + " " + txtEmail.getText());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSuspenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspenderActionPerformed
        MtoResponsable mto = new MtoResponsable();
        if (mto.suspenderResponsable()) {  
            JOptionPane.showMessageDialog(null, "El usuario ha sido suspendido de forma exitosa.","Exito",JOptionPane.INFORMATION_MESSAGE);
            txtBuscar.setText("");
            String busqueda = txtBuscar.getText();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
            tResponsables.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(busqueda));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
        vaciarCampos();
        vaciarTabla();
        mostrarResponsables();
    }//GEN-LAST:event_btnSuspenderActionPerformed

    private void tResponsablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tResponsablesMouseClicked
        //Obtener fila seleccionada
        int fila = tResponsables.getSelectedRow();
        
        //Creando objeto de controlador
        CtrlResponsable ctr = new CtrlResponsable();
        MtoResponsable mto = new MtoResponsable();
        ctr.setIdResponsable(Integer.parseInt((String)tResponsables.getValueAt(fila, 0)));
        
        mto.obtenerIdEstado();
        if (ctr.getIdEstado() == 3) {
            btnActualizar.setEnabled(false);
            btnSuspender.setEnabled(false);
            btnCorreo.setEnabled(false);
            btnActivar.setEnabled(true);
        }else{
            btnActualizar.setEnabled(true);
            btnSuspender.setEnabled(true);
            btnCorreo.setEnabled(true);
            btnActivar.setEnabled(false);
        }
        
        //Obteniendo valores de la tabla
        txtNombre.setText(String.valueOf(tResponsables.getValueAt(fila, 1)));
        txtApellido.setText(String.valueOf(tResponsables.getValueAt(fila, 2)));
        txtDui.setText(String.valueOf(tResponsables.getValueAt(fila, 3)));
        txtTelefono.setText(String.valueOf(tResponsables.getValueAt(fila, 4)));
        txtEmail.setText(String.valueOf(tResponsables.getValueAt(fila, 5)));
        cbParentesco.setSelectedItem(String.valueOf(tResponsables.getValueAt(fila, 6)));
        System.out.println(ctr.getIdResponsable());
    }//GEN-LAST:event_tResponsablesMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String busqueda = txtBuscar.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
        tResponsables.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(busqueda));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        val.verificarEspeciales(evt);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        MtoResponsable mto = new MtoResponsable();
        if (mto.activarResponsable()) {  
            JOptionPane.showMessageDialog(null, "El responsable ha sido activado de forma exitosa.","Exito",JOptionPane.INFORMATION_MESSAGE);
            txtBuscar.setText("");
            String busqueda = txtBuscar.getText();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
            tResponsables.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(busqueda));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
        vaciarCampos();
        vaciarTabla();
        mostrarResponsables();
        
    }//GEN-LAST:event_btnActivarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        val.verificarLetras(evt);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        val.verificarLetras(evt);
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_txtEmailKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnSuspender;
    private javax.swing.JComboBox<String> cbParentesco;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayer1;
    private javax.swing.JLayeredPane jLayer2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tResponsables;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
