/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CtrlConducta;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Conexion;
import modelo.MtoConducta;
import modelo.Validaciones;
import controlador.CtrlLoginUsuario;
import modelo.MtoBitacoras;

/**
 *
 * @author katy0
 */
public class frmGestionarConducta extends javax.swing.JInternalFrame {

    //Llamando clases
    Validaciones val = new Validaciones();
    CtrlConducta conductaCtrl = new CtrlConducta();
    MtoConducta conducta = new MtoConducta();
    CtrlLoginUsuario mod;

    //Declarando variables
    int idGS;
    int idEstudiante;

    //Modelo de la tabla
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form GestionarConductaForm
     */
    public frmGestionarConducta() {
        initComponents();

    }

    public frmGestionarConducta(CtrlLoginUsuario mod) {

        this.mod = mod;
        initComponents();
        System.out.println(mod.getId_usuario());
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        tConducta.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 18));
        tConducta.getTableHeader().setOpaque(false);
        tConducta.getTableHeader().setBackground(new Color(33, 37, 41));
        tConducta.getTableHeader().setForeground(new Color(254, 254, 254));
        jId.setVisible(false);

        //LlenandoCombobox
        this.llenarAnio();
        this.llenarGradoSeccion();
        this.llenarEstudiante();

        //Creando modelo de la tabla
        modelo.addColumn("Observacion");
        modelo.addColumn("Estudiante");
        modelo.addColumn("Fecha");
        tConducta.setModel(modelo);

        //Mostrando tabla
        this.mostrarConducta();

        //Personalizando jCalendar
        jCalendario.getJCalendar().setForeground(new Color(254, 254, 254));
        jCalendario.getJCalendar().setSundayForeground(Color.WHITE);
        jCalendario.getJCalendar().setWeekdayForeground(Color.WHITE);
        jCalendario.getJCalendar().setDecorationBackgroundVisible(false);
        jCalendario.getJCalendar().setWeekOfYearVisible(false);
        jCalendario.getJCalendar().setBackground(Color.WHITE);
        jCalendario.getJCalendar().setPreferredSize(new Dimension(450, 450));

        //Deshabilitando botones 
        jActualizar.setEnabled(false);
        jEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tConducta = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jObservacion = new javax.swing.JTextArea();
        jId = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        cbAño = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbGradoSeccion = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbEstudiante = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jFecha = new javax.swing.JTextField();
        jCalendario = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(33, 37, 41));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Gestionar Conducta ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Observación:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(33, 37, 41));
        btnLimpiar.setForeground(new java.awt.Color(254, 254, 254));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLimpiarDefault.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnLimpiarRollover.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 140, 70));

        tConducta.setBackground(new java.awt.Color(33, 37, 41));
        tConducta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tConducta.setForeground(new java.awt.Color(255, 255, 255));
        tConducta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tConducta.setFocusable(false);
        tConducta.setGridColor(new java.awt.Color(64, 65, 65));
        tConducta.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tConducta.setRowHeight(30);
        tConducta.setSelectionBackground(new java.awt.Color(45, 252, 119));
        tConducta.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tConducta.setShowVerticalLines(false);
        tConducta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tConductaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tConducta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 950, 280));

        btnAgregar.setBackground(new java.awt.Color(33, 37, 41));
        btnAgregar.setForeground(new java.awt.Color(254, 254, 254));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAgregar_default.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAgregar_rollover.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 140, 70));

        jActualizar.setBackground(new java.awt.Color(33, 37, 41));
        jActualizar.setForeground(new java.awt.Color(254, 254, 254));
        jActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_default.png"))); // NOI18N
        jActualizar.setBorder(null);
        jActualizar.setContentAreaFilled(false);
        jActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_rollover.png"))); // NOI18N
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 140, 70));

        jEliminar.setBackground(new java.awt.Color(33, 37, 41));
        jEliminar.setForeground(new java.awt.Color(254, 254, 254));
        jEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEliminarDefault.png"))); // NOI18N
        jEliminar.setBorder(null);
        jEliminar.setContentAreaFilled(false);
        jEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEliminarRollover.png"))); // NOI18N
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 140, 70));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Digite lo que desea buscar:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, 20));

        jBuscar.setBackground(new java.awt.Color(33, 37, 41));
        jBuscar.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jBuscar.setForeground(new java.awt.Color(254, 254, 254));
        jBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jBuscarKeyTyped(evt);
            }
        });
        getContentPane().add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 580, 30));

        jObservacion.setBackground(new java.awt.Color(33, 37, 41));
        jObservacion.setColumns(20);
        jObservacion.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jObservacion.setForeground(new java.awt.Color(255, 255, 255));
        jObservacion.setRows(5);
        jObservacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 36, 36)));
        jScrollPane2.setViewportView(jObservacion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 330, 240));
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 60, -1));

        jLayeredPane1.setNextFocusableComponent(jObservacion);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Año:");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(10, 10, 32, 21);

        cbAño.setBackground(new java.awt.Color(33, 37, 41));
        cbAño.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbAño.setForeground(new java.awt.Color(254, 254, 254));
        cbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAñoItemStateChanged(evt);
            }
        });
        cbAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbAñoMouseClicked(evt);
            }
        });
        cbAño.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbAñoPropertyChange(evt);
            }
        });
        jLayeredPane1.add(cbAño);
        cbAño.setBounds(10, 40, 310, 31);

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Grado/Sección:");
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(10, 80, 109, 21);

        cbGradoSeccion.setBackground(new java.awt.Color(33, 37, 41));
        cbGradoSeccion.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbGradoSeccion.setForeground(new java.awt.Color(254, 254, 254));
        cbGradoSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGradoSeccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGradoSeccionItemStateChanged(evt);
            }
        });
        cbGradoSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbGradoSeccionMouseClicked(evt);
            }
        });
        cbGradoSeccion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbGradoSeccionPropertyChange(evt);
            }
        });
        jLayeredPane1.add(cbGradoSeccion);
        cbGradoSeccion.setBounds(10, 110, 310, 31);

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Estudiante:");
        jLayeredPane1.add(jLabel13);
        jLabel13.setBounds(10, 150, 78, 21);

        cbEstudiante.setBackground(new java.awt.Color(33, 37, 41));
        cbEstudiante.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbEstudiante.setForeground(new java.awt.Color(254, 254, 254));
        cbEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPane1.add(cbEstudiante);
        cbEstudiante.setBounds(10, 180, 310, 31);

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Fecha:");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(10, 220, 48, 21);

        jFecha.setBackground(new java.awt.Color(33, 37, 41));
        jFecha.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jFecha.setForeground(new java.awt.Color(254, 254, 254));
        jFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jFecha.setDisabledTextColor(new java.awt.Color(254, 254, 254));
        jFecha.setEnabled(false);
        jFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFechaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFechaKeyTyped(evt);
            }
        });
        jLayeredPane1.add(jFecha);
        jFecha.setBounds(10, 250, 260, 30);

        jCalendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarioPropertyChange(evt);
            }
        });
        jLayeredPane1.add(jCalendario);
        jCalendario.setBounds(270, 250, 50, 29);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 320, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Validaciones">
    private void jBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyTyped

    }//GEN-LAST:event_jBuscarKeyTyped

    private void jFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFechaKeyTyped

    }//GEN-LAST:event_jFechaKeyTyped

    private void jFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFechaKeyPressed

    }//GEN-LAST:event_jFechaKeyPressed

    private void jBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyPressed

    }//GEN-LAST:event_jBuscarKeyPressed

    private void cbAñoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbAñoPropertyChange

    }//GEN-LAST:event_cbAñoPropertyChange

    private void cbAñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbAñoMouseClicked

    }//GEN-LAST:event_cbAñoMouseClicked

    private void cbGradoSeccionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbGradoSeccionPropertyChange

    }//GEN-LAST:event_cbGradoSeccionPropertyChange

    private void cbGradoSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbGradoSeccionMouseClicked

    }//GEN-LAST:event_cbGradoSeccionMouseClicked

    private void cbGradoSeccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGradoSeccionItemStateChanged
        this.llenarEstudiante();
    }//GEN-LAST:event_cbGradoSeccionItemStateChanged

    private void cbAñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAñoItemStateChanged
        this.llenarGradoSeccion();
    }//GEN-LAST:event_cbAñoItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (jObservacion.getText().trim().isEmpty() || jFecha.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vacios.", "Rellene los campos faltantes.", JOptionPane.WARNING_MESSAGE);
        } else {

            //Dividiendo el apellido y el nombre
            String estudiante = cbEstudiante.getItemAt(cbEstudiante.getSelectedIndex());
            String[] parte = estudiante.split("-");
            String apellido = parte[0];
            String nombre = parte[1];

            //Obteniendo id del estudiante
            idEstudiante = conducta.obtenerIdEstudiante(apellido, nombre);

            //Obteniendo el último id
            int idConducta = conducta.obtenerUltimoId() + 1;

            //Seteando todos los valores
            conductaCtrl.setIdConducta(idConducta);
            conductaCtrl.setObservacion(jObservacion.getText());
            conductaCtrl.setIdEstudiante(idEstudiante);
            conductaCtrl.setFecha(jFecha.getText());

            //Ejecutando mantenimiento 
            if (conducta.insertarConducta()) {
                JOptionPane.showMessageDialog(null, "Ha agregado los datos correctamente");
                MtoBitacoras add = new MtoBitacoras();
                int id = add.capturarIdBitacora() + 1;
                mod.setId_usuario(mod.getId_usuario());
                mod.setId_bitacora(id);
                add.agregarBitacoraAgregar(mod);
                this.limpiarTabla();
                this.mostrarConducta();
                this.limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se han agregado los datos correctamente");
            }

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jCalendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarioPropertyChange
        try {
            String dia = Integer.toString(jCalendario.getCalendar().get(Calendar.DATE));
            String año = Integer.toString(jCalendario.getCalendar().get(Calendar.YEAR));
            int mesInt = jCalendario.getCalendar().get(Calendar.MONTH) + 1;
            String mes = Integer.toString(mesInt);
            String fecha = (mes + "-" + dia + "-" + año);
            jFecha.setText(fecha);

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jCalendarioPropertyChange

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed

        //Validando campos vacios
        if (jObservacion.getText().trim().isEmpty() || jFecha.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vacios.", "Rellene los campos faltantes.", JOptionPane.WARNING_MESSAGE);
        } else {

            //Dividiendo el apellido y el nombre
            String estudiante = cbEstudiante.getItemAt(cbEstudiante.getSelectedIndex());
            String[] parte = estudiante.split("-");
            String apellido = parte[0];
            String nombre = parte[1];

            //Obteniendo id del estudiante
            idEstudiante = conducta.obtenerIdEstudiante(apellido, nombre);

            //Seteando todos los valores
            conductaCtrl.setIdConducta(Integer.parseInt(jId.getText()));
            conductaCtrl.setObservacion(jObservacion.getText());
            conductaCtrl.setIdEstudiante(idEstudiante);
            conductaCtrl.setFecha(jFecha.getText());

            //Ejecutando mantemiento 
            if (conducta.actualizarConducta()) {
                JOptionPane.showMessageDialog(null, "Ha actualizado los datos correctamente");
                MtoBitacoras add = new MtoBitacoras();
                int id = add.capturarIdBitacora() + 1;
                mod.setId_usuario(mod.getId_usuario());
                mod.setId_bitacora(id);
                add.agregarBitacoraActualizar(mod);

            } else {
                JOptionPane.showMessageDialog(null, "No se han actualizado los datos correctamente");
            }

            this.limpiarTabla();
            this.mostrarConducta();
            this.limpiarCampos();
            this.reiniciarBusqueda();
        }
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed

        if (jId.getText().trim().isEmpty() || jObservacion.getText().trim().isEmpty() || jFecha.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vacios.", "Rellene los campos faltantes.", JOptionPane.WARNING_MESSAGE);
        } else {

            conductaCtrl.setIdConducta(Integer.parseInt(jId.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este resgistro?",
                    "Atención", JOptionPane.YES_NO_OPTION);
            if (eliminar == 0) {

                if (conducta.eliminarConducta()) {
                    JOptionPane.showMessageDialog(null, "Ha eliminado los datos correctamente");
                    MtoBitacoras add = new MtoBitacoras();
                    int id = add.capturarIdBitacora() + 1;
                    mod.setId_usuario(mod.getId_usuario());
                    mod.setId_bitacora(id);
                    add.agregarBitacoraEliminar(mod);

                } else {
                    JOptionPane.showMessageDialog(null, "No se han eliminado los datos correctamente");
                }
            }
        }

        this.limpiarTabla();
        this.mostrarConducta();
        this.limpiarCampos();
        this.reiniciarBusqueda();
    }//GEN-LAST:event_jEliminarActionPerformed

    private void tConductaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tConductaMouseClicked

        //Deshabilitando botones 
        jActualizar.setEnabled(true);
        jEliminar.setEnabled(true);
        btnAgregar.setEnabled(false);

        //Obteniendo el valor de la fila
        int fila = tConducta.getSelectedRow();

        //Obteniendo valores de la fila
        String observacion = String.valueOf(tConducta.getValueAt(fila, 0));
        String fecha = String.valueOf(tConducta.getValueAt(fila, 2));

        //Seteando valores a los campos
        jObservacion.setText(observacion);
        jFecha.setText(fecha);

        //Dividiendo del estudiante
        String student = String.valueOf(tConducta.getValueAt(fila, 1));
        String[] parte = student.split("-");
        String apellido = parte[0];
        String nombre = parte[1];

        //Setetando combo de grado/seccion
        String itemGS = conducta.getItemConducta(apellido, nombre);
        cbGradoSeccion.setSelectedItem(itemGS);

        //Seteando el combo de anio
        String itemAnio = conducta.getItemAnio(apellido, nombre);
        cbAño.setSelectedItem(itemAnio);

        //obteniendo id de conducta 
        int idConducta = conducta.obtenerIdConducta(observacion, fecha, apellido, nombre);
        jId.setText(String.valueOf(idConducta));
    }//GEN-LAST:event_tConductaMouseClicked

    private void jBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyReleased
        String busqueda = jBuscar.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
        tConducta.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(busqueda));
    }//GEN-LAST:event_jBuscarKeyReleased

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="LlenandoComboBox">
    //Método para combobox del año
    public void llenarAnio() {

        //Seteando modelo del combo
        cbAño.setModel(conducta.llenarAnio());

    }

    //Método para combobox de grado/seccion
    public void llenarGradoSeccion() {

        //Obteniendo parametro del año
        String anio = cbAño.getItemAt(cbAño.getSelectedIndex());
        conductaCtrl.setAnio(anio);

        //Seteando modelo del combo
        cbGradoSeccion.setModel(conducta.llenarGradoSeccion());
    }

    //Método para combobocx de estudiante
    public void llenarEstudiante() {

        //Dividiendo el grado y la seccion
        String gradoSeccion = cbGradoSeccion.getItemAt(cbGradoSeccion.getSelectedIndex());
        String[] parte = gradoSeccion.split("-");
        String grado = parte[0];
        String seccion = parte[1];

        //Obteniendo id del gradoSeccion
        idGS = conducta.obtenerIdGS(grado, seccion);
        conductaCtrl.setIdGradoSeccion(idGS);

        //Llenando el combobox
        cbEstudiante.setModel(conducta.llenarEstudiante());
    }
    //</editor-fold>

    public void reiniciarBusqueda() {
        jBuscar.setText("");
        String busqueda = jBuscar.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelo);
        tConducta.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(busqueda));
    }

    public void mostrarConducta() {
        Conexion con = new Conexion();
        Connection datos;
        try {
            datos = con.conectar();
            String sql = "SELECT c.observacion, CONCAT(e.apellido,'-',e.nombre) as Estudiante, c.fecha FROM conducta c, estudiante e WHERE c.id_estudiante = e.id_estudiante";
            PreparedStatement dato = datos.prepareStatement(sql);
            ResultSet rs = dato.executeQuery();
            while (rs.next()) {
                Object fila[] = {rs.getString(1), rs.getString(2), rs.getString(3)};
                modelo.addRow(fila);
            }
            tConducta.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void limpiarTabla() {
        //Limpiar tabla
        int filas = tConducta.getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
    }

    public void limpiarCampos() {

        //limpiando campos
        jObservacion.setText("");
        jId.setText("");
        jFecha.setText("");
        jBuscar.setText("");

        //Deshabilitando botones 
        jActualizar.setEnabled(false);
        jEliminar.setEnabled(false);
        btnAgregar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbAño;
    private javax.swing.JComboBox<String> cbEstudiante;
    private javax.swing.JComboBox<String> cbGradoSeccion;
    private javax.swing.JButton jActualizar;
    private javax.swing.JTextField jBuscar;
    private com.toedter.calendar.JDateChooser jCalendario;
    private javax.swing.JButton jEliminar;
    private javax.swing.JTextField jFecha;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextArea jObservacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tConducta;
    // End of variables declaration//GEN-END:variables
}
