/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CtrlRecuContra;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.RecuContra;
import modelo.Validaciones;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author eduardxlr
 */
public class frmRecuPreguntas extends javax.swing.JFrame {

    Validaciones val = new Validaciones();
    //Llamando clases
    CtrlRecuContra recuCtrl = new CtrlRecuContra();
    RecuContra recu = new RecuContra();
    
    
    /**
     * Creates new form RecuPreguntasForm
     */
    public frmRecuPreguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        j1.setEnabled(false);
        j2.setEnabled(false);
        j3.setEnabled(false);
        j4.setEnabled(false);
        btnAceptar.setEnabled(false);
        jNueva.setEnabled(false);
        jConfirmar.setEnabled(false);
        btnAcep.setEnabled(false);
        cbRespuestas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        j4 = new javax.swing.JTextField();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        jUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAcep = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        cbPregunta4 = new javax.swing.JComboBox<>();
        cbPregunta3 = new javax.swing.JComboBox<>();
        cbPregunta2 = new javax.swing.JComboBox<>();
        cbPregunta1 = new javax.swing.JComboBox<>();
        jConfirmar = new javax.swing.JPasswordField();
        jNueva = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbRespuestas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Quicksand", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Recuperación de Contraseña mediante Preguntas de Seguridad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(33, 37, 41));
        jSeparator1.setForeground(new java.awt.Color(45, 255, 120));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 1290, 10));

        j4.setBackground(new java.awt.Color(33, 37, 41));
        j4.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        j4.setForeground(new java.awt.Color(254, 254, 254));
        j4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        j4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                j4KeyTyped(evt);
            }
        });
        jPanel1.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, 340, 30));

        j1.setBackground(new java.awt.Color(33, 37, 41));
        j1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        j1.setForeground(new java.awt.Color(254, 254, 254));
        j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        j1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                j1KeyTyped(evt);
            }
        });
        jPanel1.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 340, 30));

        j2.setBackground(new java.awt.Color(33, 37, 41));
        j2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        j2.setForeground(new java.awt.Color(254, 254, 254));
        j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        j2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                j2KeyTyped(evt);
            }
        });
        jPanel1.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 340, 30));

        j3.setBackground(new java.awt.Color(33, 37, 41));
        j3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        j3.setForeground(new java.awt.Color(254, 254, 254));
        j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        j3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                j3KeyTyped(evt);
            }
        });
        jPanel1.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 340, 30));

        jUsuario.setBackground(new java.awt.Color(33, 37, 41));
        jUsuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jUsuario.setForeground(new java.awt.Color(254, 254, 254));
        jUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 73, 73), 1, true));
        jUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 210, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Nueva contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Confirmar contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, -1, -1));

        jLabel6.setFont(new java.awt.Font("Quicksand", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Usuario a recuperar:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        btnAcep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAceptar_rollover.png"))); // NOI18N
        btnAcep.setBorder(null);
        btnAcep.setContentAreaFilled(false);
        btnAcep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAcep.setFocusPainted(false);
        btnAcep.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAceptar_default.png"))); // NOI18N
        btnAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 180, 80));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAceptar_rollover.png"))); // NOI18N
        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAceptar.setFocusPainted(false);
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAceptar_default.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 180, 80));

        cbPregunta4.setBackground(new java.awt.Color(33, 37, 41));
        cbPregunta4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        cbPregunta4.setForeground(new java.awt.Color(255, 255, 255));
        cbPregunta4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregunta 4", " " }));
        cbPregunta4.setBorder(null);
        cbPregunta4.setEnabled(false);
        jPanel1.add(cbPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 430, -1));

        cbPregunta3.setBackground(new java.awt.Color(33, 37, 41));
        cbPregunta3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        cbPregunta3.setForeground(new java.awt.Color(255, 255, 255));
        cbPregunta3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregunta 3", " " }));
        cbPregunta3.setBorder(null);
        cbPregunta3.setEnabled(false);
        jPanel1.add(cbPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 430, -1));

        cbPregunta2.setBackground(new java.awt.Color(33, 37, 41));
        cbPregunta2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        cbPregunta2.setForeground(new java.awt.Color(255, 255, 255));
        cbPregunta2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregunta 2", " " }));
        cbPregunta2.setBorder(null);
        cbPregunta2.setEnabled(false);
        jPanel1.add(cbPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 430, -1));

        cbPregunta1.setBackground(new java.awt.Color(33, 37, 41));
        cbPregunta1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        cbPregunta1.setForeground(new java.awt.Color(255, 255, 255));
        cbPregunta1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregunta 1", "Pregunta 2", " " }));
        cbPregunta1.setBorder(null);
        cbPregunta1.setEnabled(false);
        jPanel1.add(cbPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 430, -1));

        jConfirmar.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.add(jConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 200, 30));

        jNueva.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.add(jNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 200, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Conteste las preguntas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RecuadroRecuCorreo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RecuadroRecuCorreo.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backpng.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back_rollover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 180, 80));

        jLabel12.setFont(new java.awt.Font("Quicksand", 1, 32)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("1");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RecuadroHoraFecha.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Recuadro1RecuAdmin.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        jLabel14.setFont(new java.awt.Font("Quicksand", 1, 32)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("2");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RecuadroRecuCorreo.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVerificar_rollover-1.png"))); // NOI18N
        btnVerificar.setBorder(null);
        btnVerificar.setContentAreaFilled(false);
        btnVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerificar.setFocusPainted(false);
        btnVerificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVerificar_default.png"))); // NOI18N
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 180, 80));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RecuadroRecuCorreo.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        cbRespuestas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbRespuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        //Validando campos vacios
        if ((j1.getText().trim().isEmpty()) || (j2.getText().trim().isEmpty()) || (j3.getText().trim().isEmpty()) || 
                (j4.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Rellene los campos faltantes.","Campos vacios",JOptionPane.WARNING_MESSAGE);
        } else {
            
            //Verificando respuestas
            if (this.verificarRespuestas()) {
                
                JOptionPane.showMessageDialog(null, "Las respuesas ingresadas se han verificado correctamente","Respuetas correctas",JOptionPane.INFORMATION_MESSAGE);
                //Habilitando botones
                jUsuario.setEnabled(false);
                btnVerificar.setEnabled(false);
                j1.setEnabled(false);
                j2.setEnabled(false);
                j3.setEnabled(false);
                j4.setEnabled(false);
                btnAceptar.setEnabled(false);
                jNueva.setEnabled(true);
                jConfirmar.setEnabled(true);
                btnAcep.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepActionPerformed
       //Validando campos vacios
        if (jNueva.getText().trim().isEmpty() || jConfirmar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Rellene los campos faltantes.","Campos vacios.",JOptionPane.WARNING_MESSAGE);
        } else {
            
            String nueva = new String(jNueva.getPassword());
            String confirmar = new String(jConfirmar.getPassword());
            
            //Verificando que sean igual 
            if (nueva.equals(confirmar)) {
                
                //Reestableciendo contraseña
                String contra = new String(jConfirmar.getPassword());
                String encriptado=DigestUtils.sha1Hex(contra);
                
                recuCtrl.setNuevaContra(encriptado);
                
                if (recu.cambiarContra()) {
                    JOptionPane.showMessageDialog(null, "La contraseña se ha cambiado correctamente","Contraseña actualizada.",JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    frmLogin formulario = null;
                    try {
                        formulario = new frmLogin();
                    } catch (UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(frmRecuAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    formulario.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "La contraseña no se ha cambiado correctamente","Contraseña no actualizada.",JOptionPane.WARNING_MESSAGE);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.","Contraseñas incorrectas.",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAcepActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.setVisible(false);
       frmMenuRecuperacion formulario = new frmMenuRecuperacion();
       formulario.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        
        //Validando campos vacios
        if (jUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Rellene los campos faltantes.","Campos vacios",JOptionPane.WARNING_MESSAGE);
        } else {
            
            //Enviando datos al constructor
            recuCtrl.setUsuario(jUsuario.getText());
            
            if (recu.obtenerIdUsuario()) {
                
                //Llenanco combobox de preguntas
                cbPregunta1.setModel(recu.llenarPreguntas());
                cbPregunta2.setModel(recu.llenarPreguntas());
                cbPregunta3.setModel(recu.llenarPreguntas());
                cbPregunta4.setModel(recu.llenarPreguntas());

                
                cbPregunta1.setSelectedIndex(0);
                cbPregunta2.setSelectedIndex(1);
                cbPregunta3.setSelectedIndex(2);
                cbPregunta4.setSelectedIndex(3);
                
                cbRespuestas.setModel(recu.llenarRespuestas());
                
                //Habilitando botones
                jUsuario.setEnabled(false);
                btnVerificar.setEnabled(false);
                j1.setEnabled(true);
                j2.setEnabled(true);
                j3.setEnabled(true);
                j4.setEnabled(true);
                btnAceptar.setEnabled(true);
            }
        }
        
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    public boolean verificarRespuestas(){
        boolean resp = false;
        
        if ((j1.getText().equals(cbRespuestas.getItemAt(cbRespuestas.getSelectedIndex())))) {
            cbRespuestas.setSelectedIndex(1);
            if ((j2.getText().equals(cbRespuestas.getItemAt(cbRespuestas.getSelectedIndex())))) {
                cbRespuestas.setSelectedIndex(2);
                if ((j3.getText().equals(cbRespuestas.getItemAt(cbRespuestas.getSelectedIndex())))) {
                    cbRespuestas.setSelectedIndex(3);
                    if ((j4.getText().equals(cbRespuestas.getItemAt(cbRespuestas.getSelectedIndex())))) {
                        
                        resp = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "La cuarta respuesta no es correcta","Respuesta incorrecta",JOptionPane.WARNING_MESSAGE);
                        cbRespuestas.setSelectedIndex(0);
                    }
                } else {
                      JOptionPane.showMessageDialog(null, "La tercera respuesta no es correcta","Respuesta incorrecta",JOptionPane.WARNING_MESSAGE);
                      cbRespuestas.setSelectedIndex(0);
                }
            } else {
              JOptionPane.showMessageDialog(null, "La segunda respuesta no es correcta","Respuesta incorrecta",JOptionPane.WARNING_MESSAGE);
              cbRespuestas.setSelectedIndex(0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La primera respuesta no es correcta","Respuesta incorrecta",JOptionPane.WARNING_MESSAGE);
            cbRespuestas.setSelectedIndex(0);
        }
        
        return resp;
    }
    
    //<editor-fold defaultstate="collapsed" desc="Validaciones">
    private void jUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsuarioKeyTyped
        val.verificarEspeciales(evt);
    }//GEN-LAST:event_jUsuarioKeyTyped

    private void j1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j1KeyTyped
        val.verificarAlfanumerico(evt);
    }//GEN-LAST:event_j1KeyTyped

    private void j2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j2KeyTyped
        val.verificarAlfanumerico(evt);
    }//GEN-LAST:event_j2KeyTyped

    private void j3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j3KeyTyped
        val.verificarAlfanumerico(evt);
    }//GEN-LAST:event_j3KeyTyped

    private void j4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j4KeyTyped
        val.verificarAlfanumerico(evt);
    }//GEN-LAST:event_j4KeyTyped

    private void jUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsuarioKeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_jUsuarioKeyPressed

    private void j1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j1KeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_j1KeyPressed

    private void j2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j2KeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_j2KeyPressed

    private void j3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j3KeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_j3KeyPressed

    private void j4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j4KeyPressed
        val.verificarPegar(evt);
    }//GEN-LAST:event_j4KeyPressed
    //</editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecuPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecuPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecuPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecuPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecuPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcep;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox<String> cbPregunta1;
    private javax.swing.JComboBox<String> cbPregunta2;
    private javax.swing.JComboBox<String> cbPregunta3;
    private javax.swing.JComboBox<String> cbPregunta4;
    private javax.swing.JComboBox<String> cbRespuestas;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JButton jButton3;
    private javax.swing.JPasswordField jConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jNueva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jUsuario;
    // End of variables declaration//GEN-END:variables
}
