/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CtrlEstudiante;
import controlador.CtrlLoginUsuario;
import controlador.CtrlNotas;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Conexion;
import modelo.MtoEstudiante;
import modelo.MtoNotas;
import modelo.Validaciones;

/**
 *
 * @author katy0
 */
public class FrmTrasladoAlumnos extends javax.swing.JInternalFrame {

    //Llamando clases
    MtoEstudiante estudiante = new MtoEstudiante();
    CtrlEstudiante estudianteCtrl = new CtrlEstudiante();
    
    //Modelo de la tabla
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
    
    public FrmTrasladoAlumnos() {
        initComponents();
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        
        tNotasPendientes.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 18));
        tNotasPendientes.getTableHeader().setOpaque(false);
        tNotasPendientes.getTableHeader().setBackground(new Color(33, 37, 41));
        tNotasPendientes.getTableHeader().setForeground(new Color(254,254,254));
        
        modelo.addColumn("Estudiante");
        modelo.addColumn("Indicador");
        modelo.addColumn("Trimestre");
        tNotasPendientes.setModel(modelo);
        this.centrarColumnas();
        
        
        //Llenando combobox
        this.llenarAnio();
        this.llenarGradoSeccion();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        cbGS = new javax.swing.JComboBox<>();
        cbAño = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbGS2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbAño2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnActualizar3 = new javax.swing.JButton();
        btnActualizar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tNotasPendientes = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 37, 41));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Traslado de Alumnos para el Siguiente Año");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, -1));

        jPanel2.setBackground(new java.awt.Color(33, 37, 41));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(119, 119, 119), 1, true), "Paso 1: Verificación de Notas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVerificar_rollover-1.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusable(false);
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVerificar_default.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, 60));

        cbGS.setBackground(new java.awt.Color(33, 37, 41));
        cbGS.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbGS.setForeground(new java.awt.Color(254, 254, 254));
        cbGS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGSItemStateChanged(evt);
            }
        });
        cbGS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbGSKeyPressed(evt);
            }
        });
        jPanel2.add(cbGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));

        cbAño.setBackground(new java.awt.Color(33, 37, 41));
        cbAño.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbAño.setForeground(new java.awt.Color(254, 254, 254));
        cbAño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAñoItemStateChanged(evt);
            }
        });
        cbAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbAñoKeyPressed(evt);
            }
        });
        jPanel2.add(cbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 250, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(254, 254, 254));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Año:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Grado que va a trasladar:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 330, 270));

        jPanel3.setBackground(new java.awt.Color(33, 37, 41));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(119, 119, 119), 1, true), "Paso 2: Traslado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbGS2.setBackground(new java.awt.Color(33, 37, 41));
        cbGS2.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbGS2.setForeground(new java.awt.Color(254, 254, 254));
        cbGS2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGS2ItemStateChanged(evt);
            }
        });
        cbGS2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbGS2KeyPressed(evt);
            }
        });
        jPanel3.add(cbGS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(254, 254, 254));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Destino:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, -1));

        cbAño2.setBackground(new java.awt.Color(33, 37, 41));
        cbAño2.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbAño2.setForeground(new java.awt.Color(254, 254, 254));
        cbAño2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAño2ItemStateChanged(evt);
            }
        });
        cbAño2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbAño2KeyPressed(evt);
            }
        });
        jPanel3.add(cbAño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 250, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Año:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, -1));

        btnActualizar3.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar3.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_default.png"))); // NOI18N
        btnActualizar3.setBorder(null);
        btnActualizar3.setContentAreaFilled(false);
        btnActualizar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar3.setFocusable(false);
        btnActualizar3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_rollover.png"))); // NOI18N
        btnActualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 330, 270));

        btnActualizar2.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar2.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnReiniciarProcesoDefault.png"))); // NOI18N
        btnActualizar2.setBorder(null);
        btnActualizar2.setContentAreaFilled(false);
        btnActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar2.setFocusable(false);
        btnActualizar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnReiniciarProcesoRollover.png"))); // NOI18N
        btnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, 60));

        tNotasPendientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tNotasPendientes.setBackground(new java.awt.Color(33, 37, 41));
        tNotasPendientes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tNotasPendientes.setForeground(new java.awt.Color(255, 255, 255));
        tNotasPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tNotasPendientes.setFocusable(false);
        tNotasPendientes.setGridColor(new java.awt.Color(51, 51, 51));
        tNotasPendientes.setRequestFocusEnabled(false);
        tNotasPendientes.setRowHeight(30);
        tNotasPendientes.setRowMargin(0);
        tNotasPendientes.setSelectionBackground(new java.awt.Color(45, 252, 119));
        tNotasPendientes.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tNotasPendientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tNotasPendientes.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tNotasPendientes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1000, 330));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Notas pendientes de ingresar:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1000, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbGSKeyPressed
     
    }//GEN-LAST:event_cbGSKeyPressed

    private void cbGSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGSItemStateChanged
        
    }//GEN-LAST:event_cbGSItemStateChanged
    
    
    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        estudianteCtrl.setAnioSeccion(cbAño.getItemAt(cbAño.getSelectedIndex()));
        
        //Dividiendo el grado y la seccion
        String gradoSeccion = cbGS.getItemAt(cbGS.getSelectedIndex());
        String[] parte = gradoSeccion.split("-");
        String grado = parte[0];
        String seccion = parte[1];
        estudiante.obtenerIdGS(grado, seccion);
        
        this.limpiarTabla();
        this.mostrarNotasPendientes();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbAñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAñoItemStateChanged
       this.llenarGradoSeccion();
    }//GEN-LAST:event_cbAñoItemStateChanged

    private void cbAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbAñoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAñoKeyPressed

    private void btnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar2ActionPerformed

    private void cbGS2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGS2ItemStateChanged
        this.llenarGradoSeccion();
    }//GEN-LAST:event_cbGS2ItemStateChanged

    private void cbGS2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbGS2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGS2KeyPressed

    private void cbAño2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAño2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAño2ItemStateChanged

    private void cbAño2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbAño2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAño2KeyPressed

    private void btnActualizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar3ActionPerformed

    
    //Método para combobox del año
    public void llenarAnio() {

        //Seteando modelo del combo
        cbAño.setModel(estudiante.llenarAnio());
        cbAño2.setModel(estudiante.llenarAnio());
    }
    

    //Método para combobox de grado/seccion
    public void llenarGradoSeccion() {

        //Obteniendo parametro del año
        String anio = cbAño.getItemAt(cbAño.getSelectedIndex());
        estudianteCtrl.setAnioSeccion(anio);

        //Seteando modelo del combo
        cbGS.setModel(estudiante.llenarGS());
        cbGS2.setModel(estudiante.llenarGS());
        
    }
    
    public void centrarColumnas(){
        centrado.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < 3; i++) {
            tNotasPendientes.getColumnModel().getColumn(i).setCellRenderer(centrado);
        }
    }
    
    public void mostrarNotasPendientes(){
        Conexion con = new Conexion();
        Connection datos;
        try
        {
            datos = con.conectar();
            String sql = "SELECT CONCAT(e.apellido,'-',e.nombre)as estudiante, i.indicador, t.trimestre FROM estudiante e, indicador_logro i, nota n, trimestre t, grado_seccion gs WHERE i.id_indicador = n.id_indicador AND n.id_estudiante = e.id_estudiante AND n.id_trimestre = t.id_trimestre AND gs.id_grado_seccion = e.id_grado_seccion AND n.id_n_predeterminada = 4 AND e.id_grado_seccion = ?";
            PreparedStatement dato = datos.prepareStatement(sql);
            dato.setInt(1, estudianteCtrl.getIdGradoSeccion());
            ResultSet rs = dato.executeQuery();
            while(rs.next()){
                Object fila[] = {rs.getString(1), rs.getString(2), rs.getString(3)};
                modelo.addRow(fila);
            }
            tNotasPendientes.setModel(modelo);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void limpiarTabla(){
        //Limpiar tabla
        int filas = tNotasPendientes.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar2;
    private javax.swing.JButton btnActualizar3;
    private javax.swing.JComboBox<String> cbAño;
    private javax.swing.JComboBox<String> cbAño2;
    private javax.swing.JComboBox<String> cbGS;
    private javax.swing.JComboBox<String> cbGS2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tNotasPendientes;
    // End of variables declaration//GEN-END:variables
}
