/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CtrlLoginUsuario;
import controlador.CtrlNotas;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Conexion;
import modelo.MtoNotas;
import modelo.Validaciones;

/**
 *
 * @author katy0
 */
public class FrmTrasladoAlumnos extends javax.swing.JInternalFrame {

    
    public FrmTrasladoAlumnos() {
        initComponents();
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        cbNivelAcademico = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbNivelAcademico2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbNivelAcademico4 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbNivelAcademico5 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnActualizar3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnActualizar2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 37, 41));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Traslado de Alumnos para el Siguiente Año");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, -1));

        jPanel2.setBackground(new java.awt.Color(33, 37, 41));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(119, 119, 119), 1, true), "Paso 1: Verificación de Notas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVerificar_rollover-1.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusable(false);
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVerificar_default.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, 60));

        cbNivelAcademico.setBackground(new java.awt.Color(33, 37, 41));
        cbNivelAcademico.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbNivelAcademico.setForeground(new java.awt.Color(254, 254, 254));
        cbNivelAcademico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNivelAcademicoItemStateChanged(evt);
            }
        });
        cbNivelAcademico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbNivelAcademicoKeyPressed(evt);
            }
        });
        jPanel2.add(cbNivelAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Grado que va a trasladar:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, -1));

        cbNivelAcademico2.setBackground(new java.awt.Color(33, 37, 41));
        cbNivelAcademico2.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbNivelAcademico2.setForeground(new java.awt.Color(254, 254, 254));
        cbNivelAcademico2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNivelAcademico2ItemStateChanged(evt);
            }
        });
        cbNivelAcademico2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbNivelAcademico2KeyPressed(evt);
            }
        });
        jPanel2.add(cbNivelAcademico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 250, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(254, 254, 254));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Año:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 330, 270));

        jPanel3.setBackground(new java.awt.Color(33, 37, 41));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(119, 119, 119), 1, true), "Paso 2: Traslado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbNivelAcademico4.setBackground(new java.awt.Color(33, 37, 41));
        cbNivelAcademico4.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbNivelAcademico4.setForeground(new java.awt.Color(254, 254, 254));
        cbNivelAcademico4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNivelAcademico4ItemStateChanged(evt);
            }
        });
        cbNivelAcademico4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbNivelAcademico4KeyPressed(evt);
            }
        });
        jPanel3.add(cbNivelAcademico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(254, 254, 254));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Destino:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, -1));

        cbNivelAcademico5.setBackground(new java.awt.Color(33, 37, 41));
        cbNivelAcademico5.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        cbNivelAcademico5.setForeground(new java.awt.Color(254, 254, 254));
        cbNivelAcademico5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNivelAcademico5ItemStateChanged(evt);
            }
        });
        cbNivelAcademico5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbNivelAcademico5KeyPressed(evt);
            }
        });
        jPanel3.add(cbNivelAcademico5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 250, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Año:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, -1));

        btnActualizar3.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar3.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_default.png"))); // NOI18N
        btnActualizar3.setBorder(null);
        btnActualizar3.setContentAreaFilled(false);
        btnActualizar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar3.setFocusable(false);
        btnActualizar3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnActualizar_rollover.png"))); // NOI18N
        btnActualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 330, 270));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(33, 37, 41));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(119, 119, 119), 1, true), "Notas Pendientes de Ingresar:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 820, 260));

        btnActualizar2.setBackground(new java.awt.Color(33, 37, 41));
        btnActualizar2.setForeground(new java.awt.Color(254, 254, 254));
        btnActualizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnReiniciarProcesoDefault.png"))); // NOI18N
        btnActualizar2.setBorder(null);
        btnActualizar2.setContentAreaFilled(false);
        btnActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar2.setFocusable(false);
        btnActualizar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnReiniciarProcesoRollover.png"))); // NOI18N
        btnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNivelAcademicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbNivelAcademicoKeyPressed
     
    }//GEN-LAST:event_cbNivelAcademicoKeyPressed

    private void cbNivelAcademicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNivelAcademicoItemStateChanged

    }//GEN-LAST:event_cbNivelAcademicoItemStateChanged
    
    
    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbNivelAcademico2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNivelAcademico2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelAcademico2ItemStateChanged

    private void cbNivelAcademico2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbNivelAcademico2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelAcademico2KeyPressed

    private void btnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar2ActionPerformed

    private void cbNivelAcademico4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNivelAcademico4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelAcademico4ItemStateChanged

    private void cbNivelAcademico4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbNivelAcademico4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelAcademico4KeyPressed

    private void cbNivelAcademico5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNivelAcademico5ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelAcademico5ItemStateChanged

    private void cbNivelAcademico5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbNivelAcademico5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelAcademico5KeyPressed

    private void btnActualizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar2;
    private javax.swing.JButton btnActualizar3;
    private javax.swing.JComboBox<String> cbNivelAcademico;
    private javax.swing.JComboBox<String> cbNivelAcademico2;
    private javax.swing.JComboBox<String> cbNivelAcademico4;
    private javax.swing.JComboBox<String> cbNivelAcademico5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
