/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CtrlLoginUsuario;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author EDUARDO
 */
public class FrmUsuarioContenedor extends javax.swing.JFrame {

    CtrlLoginUsuario mod;
    
    public FrmUsuarioContenedor() {
        initComponents();
    }

    public FrmUsuarioContenedor(CtrlLoginUsuario mod) {
        initComponents();
        this.mod = mod;
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jAgregarUsuario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jAdministrarUsuarios = new javax.swing.JButton();
        jDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAgregarUsuarioDefault.png"))); // NOI18N
        jAgregarUsuario.setBorder(null);
        jAgregarUsuario.setContentAreaFilled(false);
        jAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAgregarUsuario.setFocusPainted(false);
        jAgregarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAgregarUsuarioRollover.png"))); // NOI18N
        jAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 260, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backpng.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back_rollover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 160, 80));

        jAdministrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGestionarUsuariosDefault.png"))); // NOI18N
        jAdministrarUsuarios.setBorder(null);
        jAdministrarUsuarios.setContentAreaFilled(false);
        jAdministrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAdministrarUsuarios.setFocusPainted(false);
        jAdministrarUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGestionarUsuariosRollover.png"))); // NOI18N
        jAdministrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdministrarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(jAdministrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 650, 260, 80));

        jDesktop.setBackground(new java.awt.Color(33, 37, 41));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elige una de las dos opciones disponibles:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoKidsAtTop.png"))); // NOI18N

        jDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addGroup(jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
        );

        jPanel1.add(jDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 728));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarUsuarioActionPerformed
        try {
            FrmAgregarUsuario usr = new FrmAgregarUsuario(mod);
            jDesktop.add(usr);
            usr.setVisible(true);
        
            Icon Imagenes;
            Imagenes = new ImageIcon(getClass().getResource("/imagenes/btnAgregarUsuarioPressed.png"));
            jAgregarUsuario.setIcon(Imagenes);
            
            Imagenes = new ImageIcon(getClass().getResource("/imagenes/btnGestionarUsuariosDefault.png"));
            jAdministrarUsuarios.setIcon(Imagenes);
        } catch (ParseException ex) {
            Logger.getLogger(FrmUsuarioContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAgregarUsuarioActionPerformed

    private void jAdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdministrarUsuariosActionPerformed
        try {
            FrmGestionarUsuarios usr = new FrmGestionarUsuarios(mod);
            jDesktop.add(usr);
            usr.setVisible(true);
            
            Icon Imagenes;
            Imagenes = new ImageIcon(getClass().getResource("/imagenes/btnAgregarUsuarioDefault.png"));
            jAgregarUsuario.setIcon(Imagenes);
            
            Imagenes = new ImageIcon(getClass().getResource("/imagenes/btnGestionarUsuariosPressed.png"));
            jAdministrarUsuarios.setIcon(Imagenes);
        } catch (ParseException ex) {
            Logger.getLogger(FrmUsuarioContenedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAdministrarUsuariosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        FrmHerramientasCont frm = new FrmHerramientasCont(mod);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarioContenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdministrarUsuarios;
    private javax.swing.JButton jAgregarUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
